# Generated by Django 6.0.7 on 2026-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_name', models.CharField(default='AIESEC LC Carthage', max_length=200)),
                ('current_term', models.CharField(default='2026-S1', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('expa_access_token', models.CharField(blank=True, default='', help_text='Token from auth.aiesec.org/developers/applications', max_length=200)),
                ('stage_idle_thresholds', models.JSONField(default=dict, help_text='{"open": 14, "matched_with_opp": 7, ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
