# Generated by Django 6.0.7 on 2026-08-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('priority', 'Priority')], db_index=True, default='active', max_length=15)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], db_index=True, default='bronze', max_length=15)),
                ('contract_start', models.DateField(blank=True, help_text='Partnership contract start date', null=True)),
                ('contract_end', models.DateField(blank=True, help_text='Partnership contract end date', null=True)),
                ('testimonials_link', models.URLField(blank=True, default='')),
                ('opportunities_page_link', models.URLField(blank=True, default='')),
                ('whatsapp_group_link', models.URLField(blank=True, default='')),
                ('vp_contact', models.CharField(blank=True, default='', help_text='Name / role / phone of VP contact', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='IR member responsible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_irs', to='members.member')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_irs', to='members.member')),
            ],
            options={
                'verbose_name': 'IR Partner',
                'verbose_name_plural': 'IR Partners',
                'ordering': ['country', 'entity_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('teaching', 'Teaching'), ('it', 'IT'), ('marketing', 'Marketing'), ('business', 'Business'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_open', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('track', models.CharField(choices=[('GT', 'Global Talent'), ('GTe', 'Global Teacher')], default='GT', help_text='Which AIESEC track this opportunity aligns with', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='partners.ir')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-is_open', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ir',
            constraint=models.UniqueConstraint(fields=('entity_name', 'country'), name='unique_ir_entity_country'),
        ),
    ]
