# Generated by Django 6.0.7 on 2026-08-03 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('socials', models.TextField(blank=True, default='', help_text='WhatsApp, Messenger, etc.')),
                ('university', models.CharField(blank=True, default='', max_length=200)),
                ('major', models.CharField(blank=True, default='', max_length=200)),
                ('year_of_study', models.CharField(blank=True, default='', max_length=50)),
                ('track', models.CharField(choices=[('GT', 'Global Talent'), ('GTe', 'Global Teacher')], db_index=True, default='GT', max_length=5)),
                ('current_stage', models.CharField(choices=[('open', 'Open'), ('matched_with_opp', 'Matched with opp'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('all_papers_done', 'All papers Done'), ('not_all_papers_done', 'Not all papers done'), ('do_papers', 'Do Papers'), ('realized', 'Realized')], db_index=True, default='open', max_length=30)),
                ('problem_flag', models.CharField(choices=[('none', 'None'), ('fix_ep_problem', 'Fix EP Problem'), ('fix_ir_problem', 'Fix IR Problem'), ('problem_fixed', 'Problem Fixed')], db_index=True, default='none', max_length=20)),
                ('term', models.CharField(default='2026-S1', help_text='e.g. 2026-S1', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('expa_sync', 'EXPA Sync')], default='manual', max_length=20)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tl_notes', models.TextField(blank=True, default='', help_text='Private notes visible only to TL and VP')),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft-delete — hidden from lists by default')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='OPS member or TL responsible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_eps', to='members.member')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_eps', to='members.member')),
                ('matched_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_eps', to='partners.opportunity')),
            ],
            options={
                'verbose_name': 'Exchange Participant',
                'verbose_name_plural': 'Exchange Participants',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('label', models.CharField(choices=[('contract', 'Contract'), ('passport', 'Passport / ID'), ('cv', 'CV'), ('acceptance', 'Acceptance Letter'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='members.member')),
                ('ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ops.ep')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='members.member')),
                ('ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ops.ep')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('open', 'Open'), ('matched_with_opp', 'Matched with opp'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('all_papers_done', 'All papers Done'), ('not_all_papers_done', 'Not all papers done'), ('do_papers', 'Do Papers'), ('realized', 'Realized')], max_length=30)),
                ('previous_stage', models.CharField(blank=True, choices=[('open', 'Open'), ('matched_with_opp', 'Matched with opp'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('all_papers_done', 'All papers Done'), ('not_all_papers_done', 'Not all papers done'), ('do_papers', 'Do Papers'), ('realized', 'Realized')], default='', max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to='members.member')),
                ('ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='ops.ep')),
            ],
            options={
                'verbose_name_plural': 'Stage histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query_params', models.JSONField(default=dict, help_text='URL query params as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('member', 'name')},
            },
        ),
    ]
