# Generated by Django 6.0.8 on 2026-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ep',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='ep',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('expa_sync', 'EXPA Sync')], db_index=True, default='manual', max_length=20),
        ),
    ]
