# Generated by Django 6.0.7 on 2026-08-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='Use {{ep.full_name}}, {{ep.track}}, {{ep.current_stage}}, {{lc_name}} as placeholders.')),
                ('trigger_stage', models.CharField(choices=[('open', 'Open'), ('matched_with_opp', 'Matched with opp'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('all_papers_done', 'All papers Done'), ('not_all_papers_done', 'Not all papers done'), ('do_papers', 'Do Papers'), ('realized', 'Realized')], help_text='Email is sent automatically when an EP enters this stage.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trigger_stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='ops.ep')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.emailtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
